### ISSUE TITLE
Add the robust error management

### ISSUE THREAD

**Issue by papac** [adjemin/mtnsmscloud-php#2]
Actualy the librairy have the basic error management.

But if this will use in big project like frameworks the error manager so important.

I propose you to create the `src\MtnSmsCloud\Exception\MtnSmsCloudException`.

```php
throw new MtnSmsCloudException
```

When you want to send the error.

**Comment by angebagui** [comment]
Send your change i will merge it's good.

**Comment by papac** [comment]
Look my modification let's me know what would you like to update.
[25bf738](https://github.com/papac/mtnsmscloud-php/commit/25bf73805e5875e92d1d35cc7075bfbc12098e6d)

**Comment by angebagui** [comment]
I have used your change, great job. I have made so change on the getMessage function in MTNSMSApi.php. Developer must know all parameters simply. 
Thanks !
